### ISSUE TITLE
constant maxLogSize 

### ISSUE THREAD

**Issue by pizirun** [kuujo/copycat#17]
The constant is defined as: private int maxLogSize = 32 * 1024^2; 
It will be evaluated as (32 * 1024) ^ 2 = 32768 ^ 2 = 32770
The cause is '^' will be parsed as Bitwise Operators.
(http://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html#jls-15.22.1)

32GB would be defined as 32 * 1024 * 1024

**Comment by jhalterman** [comment]
Thanks for the heads up. Logs are now segmented, and the default segment size is 1 gig:

https://github.com/kuujo/copycat/blob/80ff4ba2daff378c9564278bbb1d7239f3dba5ac/core/src/main/java/net/kuujo/copycat/log/Log.java#L37
