### ISSUE TITLE
Merging vertigo code into copycat

### ISSUE THREAD

**Issue by pizirun** [kuujo/copycat#18]
Is it possible to graft your vertigo code into copycat for computation engine?

**Comment by kuujo** [comment]
You're on the right track! Actually, I'm doing quite the same, but opposite. Some layers of Copycat will be used to provide fault-tolerant stateful components for Vertigo. That is, if testing proves it to be feasible, Vertigo components can (optionally) run on top of Copycat. So, I suppose the answer is yes!

It's a slow process, and I'm currently working on faster off-heap I/O for Copycat, but indeed the end goal is exactly what you mentioned.

**Comment by pizirun** [comment]
Great to know that, thanks for your work.
