### ISSUE TITLE
Are the Copycat's collections persistent?

### ISSUE THREAD

**Issue by pizirun** [kuujo/copycat#19]
BTW., Jordan I just followed you on Twitter. (for fast and easy discussion)
I'm seeking a simple solution for distributed map(k/v storage) and mq (queue), I found mapdb(www.mapdb.org), however, its communitiy version is not distributed, only embedded.
Regarding mapdb's off-heap implementation and the performance, actually, I'm try to make a broker fork and make it distributed by implementing it based on vert.x.
But I stop here when I try to implement Raft in java.

Back to the topic of the issue, are Copycat's collections log-based? That's to say, can be reload while server restart?

Thanks,
Pprun

**Comment by kuujo** [comment]
The version of Copycat that will be released within the next couple weeks (`0.6.0`) supports both in-memory and on-disk logs via the `StorageLevel` enum.

```java
Log log = Log.builder()
  .withDirectory("logs")
  .withStorageLevel(StorageLevel.DISK)
  .build();
```

When logs are stored on disk, after a failure or server restart, the logs will be replayed from disk to rebuild the state machine (e.g. a map). When logs are stored in memory, in the event of a failure or server restart, the logs will be replicated from other members of the Raft cluster so long as a majority of the cluster is alive.
