### ISSUE TITLE
Consistency

### ISSUE THREAD

**Issue by domsj** [kuujo/copycat#22]
Hi,

I just discovered this project and it looks really nice. While reading the rather long (but very good) readme I saw there are basically 3 levels of consistency defined: strong, default and weak.

A fourth level of consistency can be useful for some use cases: bounded consistency.
Bounded consistency could require the node being queried to have applied the log entries up until at least a certain index to it's statemachine.
For this to be useful a client should have a way to get the latest applied logindex.

On a related note, currently it's possible to define this attribute on the server side: `@Query(consistency=Consistency.STRONG)` ; instead it may be useful to let the client decide how consistent it wants a certain query to be. That way depending on the situation a client could perform the same query with different consistency guarantees.

As a final remark: renaming the consistency level `DEFAULT` to `LEASE` may be better?
(I do think the lease consistency is the right default.)

Regards,
Jan

**Comment by kuujo** [comment]
Hey,

Actually, this has been implemented in Copycat 0.6 (now the `master` branch). Copycat now has the following `ConsistencyLevel` modes:
* `LINEARIZABLE` - Requires reads to go through the leader and for the leader to contact a majority of the cluster
* `LINEARIZABLE_LEASE` - Requires reads to go through the leader and for the leader to have heard from a majority of the cluster within the last election timeout
* `SEQUENTIAL` - (This is the one you're talking about) Allows reads from followers, but waits until state reaching an index provided by the client
* `SERIALIZABLE` - Allows reads from followers with no restrictions on indexes

The way the `SEQUENTIAL` consistency level works is when a client submits a command or query to the cluster, the last applied index is returned to the client along with the result. When the client submits a command or query to the cluster, the client sends back the last index that it saw. So, if the client writes to index `10` and then submits a read to a follower, the follower will wait until index `10` is applied to its state machine. If the follower already applied index `12`, it will return index `12` with the result, and the next time the client submits a command or query to any node it will be guaranteed to see state at least up to index `12`.
