### ISSUE TITLE
master and 0.6.0

### ISSUE THREAD

**Issue by juaby** [kuujo/copycat#24]
like master 
not like 0.6.0

哈哈哈

**Comment by juaby** [comment]
like your idea
raft + gossip = good

**Comment by kuujo** [comment]
0.6.0 will still have asynchronous replication and read-only nodes. That will not change. The most significant changes are in aggregating various APIs and other concepts (e.g. using builders, using a single log, etc), improving the Raft protocol, and improving the log compaction algorithm.

The most significant changes to the Raft and asynchronous replication protocols are solely in the interest of safety. Operations submitted by all nodes are now linearizable, and redundancy in the asynchronous replication protocol is reduced by coordinating replication through Raft.

**Comment by juaby** [comment]
thanks， I am reading the current version of the 0.6.0，and I want to say, great.
come on;

**Comment by kuujo** [comment]
Hey,

So now 0.6.0 has passive (read-only) members using a refactored asynchronous replication protocol. It no longer uses a gossip protocol; the new protocol is coordinated by the Raft algorithm to reduce redundant network traffic. Also, the new protocol takes steps to ensure asynchronous replicas do not fall more than a few seconds behind the Raft cluster.

0.6.0 is currently in the process of being tested and documented. We've been working on Jepsen tests for the last week, and I can say that it is already significantly more stable than the current master branch and will be merged into master within the next few days. After a week or two more of testing and profiling a beta version will be pushed to Maven Central.
